name: Terraform QA

on:
  workflow-run:
    workflows: ["Terraform Dev"]
    types: [completed]

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true
  TF_VERSION: "1.16.0"
  TF_VAR_location: ${{ vars.LOCATION}}
  TF_VAR_environment: ${{ vars.ENVIRONMENT}}
  TF_VAR_pod_cidr: ${{ vars.POD_CIDR}}
  TF_VAR_service_cidr: ${{ vars.SERVICE_CIDR}}
  TF_VAR_dns_service_ip: ${{ vars.DNS_SERVICE_IP}}
  TF_VAR_project_name: ${{ vars.PROJECT_NAME }}

jobs:
  plan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: qa-plan
    defaults:
      run:
        working-directory: envs/qa
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Trivy IaC Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Terraform plan
        run: terraform plan -input=false -no-color -out=tfplan | tee plan.txt

      - name: Upload plan artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-qa
          path: envs/qa/plan.txt
          retention-days: 2
  
  apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: qa
    defaults:
      run:
        working-directory: envs/qa
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform apply
        run: terraform apply -input=false -auto-approve